name: movie_vault
description: "Movie Vault – your ultimate destination for discovering and exploring your favorite movies and TV shows!"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.2
  cached_network_image: ^3.4.1
  http: ^1.2.2
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.4.2
  mask_text_input_formatter: ^2.9.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.6
  riverpod_annotation: ^2.1.5
  envied: ^1.0.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.3.2
  envied_generator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/auth/
    - assets/svg/bottom_nav/
