const kCountryLanguages = {
  "aa": "Afar",
  "ab": "Abkhaz",
  "ae": "Avestan",
  "af": "Afrikaans",
  "ak": "Akan",
  "am": "Amharic",
  "an": "Aragonese",
  "ar": "Arabic",
  "ar_ae": "Arabic (United Arab Emirates)",
  "ar_bh": "Arabic (Bahrain)",
  "ar_dz": "Arabic (Algeria)",
  "ar_eg": "Arabic (Egypt)",
  "ar_iq": "Arabic (Iraq)",
  "ar_jo": "Arabic (Jordan)",
  "ar_kw": "Arabic (Kuwait)",
  "ar_lb": "Arabic (Lebanon)",
  "ar_ly": "Arabic (Libya)",
  "ar_ma": "Arabic (Morocco)",
  "ar_om": "Arabic (Oman)",
  "ar_qa": "Arabic (Qatar)",
  "ar_sa": "Arabic (Saudi Arabia)",
  "ar_sd": "Arabic (Sudan)",
  "ar_sy": "Arabic (Syria)",
  "ar_tn": "Arabic (Tunisia)",
  "ar_ye": "Arabic (Yemen)",
  "as": "Assamese",
  "av": "Avaric",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "ba": "Bashkir",
  "be": "Belarusian",
  "be_by": "Belarusian (Belarus)",
  "bg": "Bulgarian",
  "bg_bg": "Bulgarian (Bulgaria)",
  "bh": "Bihari",
  "bi": "Bislama",
  "bm": "Bambara",
  "bn": "Bengali",
  "bo": "Tibetan Standard:Tibetan:Central",
  "br": "Breton",
  "bs": "Bosnian",
  "ca": "Catalan; Valencian",
  "ca_es": "Catalan (Spain)",
  "ce": "Chechen",
  "ch": "Chamorro",
  "cn": "Chinese",
  "co": "Corsican",
  "cr": "Cree",
  "cs": "Czech",
  "cs_cz": "Czech (Czech Republic)",
  "cu":
      "Old Church Slavonic:Church Slavic:Church Slavonic:Old Bulgarian:Old Slavonic",
  "cv": "Chuvash",
  "cy": "Welsh",
  "da": "Danish",
  "da_dk": "Danish (Denmark)",
  "de": "German",
  "de_at": "German (Austria)",
  "de_ch": "German (Switzerland)",
  "de_de": "German (Germany)",
  "de_lu": "German (Luxembourg)",
  "dv": "Divehi; Dhivehi; Maldivian;",
  "ee": "Ewe",
  "el": "Greek:Modern",
  "el_cy": "Greek (Cyprus)",
  "el_gr": "Greek (Greece)",
  "en": "English",
  "en_au": "English (Australia)",
  "en_ca": "English (Canada)",
  "en_gb": "English (United Kingdom)",
  "en_ie": "English (Ireland)",
  "en_in": "English (India)",
  "en_mt": "English (Malta)",
  "en_nz": "English (New Zealand)",
  "en_ph": "English (Philippines)",
  "en_sg": "English (Singapore)",
  "en_us": "English (United States)",
  "en_za": "English (South Africa)",
  "eo": "Esperanto",
  "es": "Spanish; Castilian",
  "es_ar": "Spanish (Argentina)",
  "es_bo": "Spanish (Bolivia)",
  "es_cl": "Spanish (Chile)",
  "es_co": "Spanish (Colombia)",
  "es_cr": "Spanish (Costa Rica)",
  "es_do": "Spanish (Dominican Republic)",
  "es_ec": "Spanish (Ecuador)",
  "es_es": "Spanish (Spain)",
  "es_gt": "Spanish (Guatemala)",
  "es_hn": "Spanish (Honduras)",
  "es_mx": "Spanish (Mexico)",
  "es_ni": "Spanish (Nicaragua)",
  "es_pa": "Spanish (Panama)",
  "es_pe": "Spanish (Peru)",
  "es_pr": "Spanish (Puerto Rico)",
  "es_py": "Spanish (Paraguay)",
  "es_sv": "Spanish (El Salvador)",
  "es_us": "Spanish (United States)",
  "es_uy": "Spanish (Uruguay)",
  "es_ve": "Spanish (Venezuela)",
  "et": "Estonian",
  "et_ee": "Estonian (Estonia)",
  "eu": "Basque",
  "fa": "Persian",
  "ff": "Fula; Fulah; Pulaar; Pular",
  "fi": "Finnish",
  "fi_fi": "Finnish (Finland)",
  "fj": "Fijian",
  "fo": "Faroese",
  "fr": "French",
  "fr_be": "French (Belgium)",
  "fr_ca": "French (Canada)",
  "fr_ch": "French (Switzerland)",
  "fr_fr": "French (France)",
  "fr_lu": "French (Luxembourg)",
  "fy": "Western Frisian",
  "ga": "Irish",
  "ga_ie": "Irish (Ireland)",
  "gd": "Scottish Gaelic; Gaelic",
  "gl": "Galician",
  "gn": "Guaraní",
  "gu": "Gujarati",
  "gv": "Manx",
  "ha": "Hausa",
  "he": "Hebrew (modern)",
  "hi": "Hindi",
  "hi_in": "Hindi (India)",
  "ho": "Hiri Motu",
  "hr": "Croatian",
  "hr_hr": "Croatian (Croatia)",
  "ht": "Haitian; Haitian Creole",
  "hu": "Hungarian",
  "hu_hu": "Hungarian (Hungary)",
  "hy": "Armenian",
  "hz": "Herero",
  "ia": "Interlingua",
  "id": "Indonesian",
  "ie": "Interlingue",
  "ig": "Igbo",
  "ii": "Nuosu",
  "ik": "Inupiaq",
  "in": "Indonesian",
  "in_id": "Indonesian (Indonesia)",
  "io": "Ido",
  "is": "Icelandic",
  "is_is": "Icelandic (Iceland)",
  "it": "Italian",
  "it_ch": "Italian (Switzerland)",
  "it_it": "Italian (Italy)",
  "iu": "Inuktitut",
  "iw": "Hebrew",
  "iw_il": "Hebrew (Israel)",
  "ja": "Japanese",
  "ja_jp": "Japanese (Japan)",
  "jv": "Javanese",
  "ka": "Georgian",
  "kg": "Kongo",
  "ki": "Kikuyu:Gikuyu",
  "kj": "Kwanyama:Kuanyama",
  "kk": "Kazakh",
  "kl": "Kalaallisut:Greenlandic",
  "km": "Khmer",
  "kn": "Kannada",
  "ko": "Korean",
  "ko_kr": "Korean (South Korea)",
  "kr": "Kanuri",
  "ks": "Kashmiri",
  "ku": "Kurdish",
  "kv": "Komi",
  "kw": "Cornish",
  "ky": "Kirghiz:Kyrgyz",
  "la": "Latin",
  "lb": "Luxembourgish:Letzeburgesch",
  "lg": "Luganda",
  "li": "Limburgish:Limburgan:Limburger",
  "ln": "Lingala",
  "lo": "Lao",
  "lt": "Lithuanian",
  "lt_lt": "Lithuanian (Lithuania)",
  "lu": "Luba-Katanga",
  "lv": "Latvian",
  "lv_lv": "Latvian (Latvia)",
  "mg": "Malagasy",
  "mh": "Marshallese",
  "mi": "Māori",
  "mk": "Macedonian",
  "mk_mk": "Macedonian (Macedonia)",
  "ml": "Malayalam",
  "mn": "Mongolian",
  "mr": "Marathi (Marāṭhī)",
  "ms": "Malay",
  "ms_my": "Malay (Malaysia)",
  "mt": "Maltese",
  "mt_mt": "Maltese (Malta)",
  "my": "Burmese",
  "na": "Nauru",
  "nb": "Norwegian Bokmål",
  "nd": "North Ndebele",
  "ne": "Nepali",
  "ng": "Ndonga",
  "nl": "Dutch",
  "nl_be": "Dutch (Belgium)",
  "nl_nl": "Dutch (Netherlands)",
  "nn": "Norwegian Nynorsk",
  "no": "Norwegian",
  "no_no": "Norwegian (Norway)",
  "nr": "South Ndebele",
  "nv": "Navajo:Navaho",
  "ny": "Chichewa; Chewa; Nyanja",
  "oc": "Occitan",
  "oj": "Ojibwe:Ojibwa",
  "om": "Oromo",
  "or": "Oriya",
  "os": "Ossetian:Ossetic",
  "pa": "Panjabi:Punjabi",
  "pi": "Pāli",
  "pl": "Polish",
  "pl_pl": "Polish (Poland)",
  "ps": "Pashto:Pushto",
  "pt": "Portuguese",
  "pt_br": "Portuguese (Brazil)",
  "pt_pt": "Portuguese (Portugal)",
  "qu": "Quechua",
  "rm": "Romansh",
  "rn": "Kirundi",
  "ro": "Romanian:Moldavian:Moldovan",
  "ro_ro": "Romanian (Romania)",
  "ru": "Russian",
  "ru_ru": "Russian (Russia)",
  "rw": "Kinyarwanda",
  "sa": "Sanskrit (Saṁskṛta)",
  "sc": "Sardinian",
  "sd": "Sindhi",
  "se": "Northern Sami",
  "sg": "Sango",
  "si": "Sinhala:Sinhalese",
  "sk": "Slovak",
  "sk_sk": "Slovak (Slovakia)",
  "sl": "Slovene",
  "sl_si": "Slovenian (Slovenia)",
  "sm": "Samoan",
  "sn": "Shona",
  "so": "Somali",
  "sq": "Albanian",
  "sq_al": "Albanian (Albania)",
  "sr": "Serbian",
  "sr_ba": "Serbian (Bosnia and Herzegovina)",
  "sr_cs": "Serbian (Serbia and Montenegro)",
  "sr_me": "Serbian (Montenegro)",
  "sr_rs": "Serbian (Serbia)",
  "ss": "Swati",
  "st": "Southern Sotho",
  "su": "Sundanese",
  "sv": "Swedish",
  "sv_se": "Swedish (Sweden)",
  "sw": "Swahili",
  "ta": "Tamil",
  "te": "Telugu",
  "tg": "Tajik",
  "th": "Thai",
  "th_th": "Thai (Thailand)",
  "ti": "Tigrinya",
  "tk": "Turkmen",
  "tl": "Tagalog",
  "tn": "Tswana",
  "to": "Tonga (Tonga Islands)",
  "tr": "Turkish",
  "tr_tr": "Turkish (Turkey)",
  "ts": "Tsonga",
  "tt": "Tatar",
  "tw": "Twi",
  "ty": "Tahitian",
  "ug": "Uighur:Uyghur",
  "uk": "Ukrainian",
  "uk_ua": "Ukrainian (Ukraine)",
  "ur": "Urdu",
  "uz": "Uzbek",
  "ve": "Venda",
  "vi": "Vietnamese",
  "vi_vn": "Vietnamese (Vietnam)",
  "vo": "Volapük",
  "wa": "Walloon",
  "wo": "Wolof",
  "xh": "Xhosa",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "za": "Zhuang:Chuang",
  "zh": "Chinese",
  "zh_cn": "Chinese (Simplified:China)",
  "zh_hk": "Chinese (Hong Kong)",
  "zh_sg": "Chinese (Singapore)",
  "zh_tw": "Chinese (Traditional:Taiwan)",
};
